# Generated by Django 2.0.2 on 2018-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='summoner_id',
            field=models.IntegerField(default=0),
        ),
    ]
