# Generated by Django 2.0.2 on 2018-03-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_auto_20180303_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='input',
            name='summoner_id',
        ),
    ]
