# Generated by Django 2.0.2 on 2018-03-05 03:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_auto_20180304_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
        ),
    ]
