# Generated by Django 2.0.2 on 2018-03-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_input_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='data',
        ),
    ]
