# Generated by Django 2.0.2 on 2018-03-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_remove_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='top_kill',
            field=models.IntegerField(default=0),
        ),
    ]
