# Generated by Django 2.0.2 on 2018-03-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0008_input_top_kill'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='region',
            field=models.CharField(choices=[('na1', 'NA1'), ('br1', 'BR1'), ('eun1', 'EUN1'), ('euw1', 'EUW1'), ('jp1', 'JP1'), ('kr', 'KR'), ('la1', 'LA1'), ('la2', 'LA2'), ('oc1', 'OC1'), ('tr1', 'TR1'), ('ru', 'RU')], default='NA1', max_length=6),
        ),
    ]
