# Generated by Django 2.0.2 on 2018-03-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0009_input_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('region', 'username')},
        ),
    ]
