# Generated by Django 2.0.2 on 2018-03-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0010_auto_20180313_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('username', 'region')},
        ),
    ]
