# Generated by Django 2.0.2 on 2018-03-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0011_auto_20180313_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='summoner_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together=set(),
        ),
    ]
