# Generated by Django 2.0.2 on 2018-03-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0014_auto_20180313_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
