# Generated by Django 2.0.2 on 2018-03-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0015_delete_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='items',
            field=models.ManyToManyField(to='mission.Item'),
        ),
    ]
