# Generated by Django 2.0.2 on 2018-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0016_auto_20180328_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.IntegerField(default=0),
        ),
    ]
