# Generated by Django 2.0.2 on 2018-04-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0019_input_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='created',
        ),
    ]
